[27 feb 2018 19:26:20,452][INFO ][][] Using a custom ConnectionKeepAliveStrategy with default duration = 'infinite' 
[27 feb 2018 19:26:20,452][INFO ][][] Using a custom ConnectionReuseStrategy based on peer HTTP headers/version 
[27 feb 2018 19:26:20,452][INFO ][][] Using a custom HttpRequestRetryHandler to delegate retry logic to JMS redelivery mechanism 
[27 feb 2018 19:26:20,452][DEBUG][][] Creating shared HTTP client 
[27 feb 2018 19:26:20,452][DEBUG][][] httpsClientProperties.getTrustURLString():[file:///D:/MyGitRepo/Dynatrace2RemedyLocalRepo/parent/dynatrace2RemedyEngine/src/main/resources/truststore.jks] 
[27 feb 2018 19:26:20,499][DEBUG][][] createTrustManagers - Initializing trust manager: dynatracetest 
[27 feb 2018 19:26:20,499][DEBUG][][] Initializing trust manager 
[27 feb 2018 19:26:20,592][DEBUG][][] --------- protocolHandShake:[TLSv1.2]-------- 
[27 feb 2018 19:26:21,201][DEBUG][][] Shared HTTP client created successfully! 
[27 feb 2018 19:26:21,201][INFO ][][] Starting IdleHTTPConnectionEvictor task (evictionPeriod=5000) 
[27 feb 2018 19:26:21,233][INFO ][][] Using a custom ConnectionKeepAliveStrategy with default duration = 'infinite' 
[27 feb 2018 19:26:21,233][INFO ][][] Using a custom ConnectionReuseStrategy based on peer HTTP headers/version 
[27 feb 2018 19:26:21,233][INFO ][][] Using a custom HttpRequestRetryHandler to delegate retry logic to JMS redelivery mechanism 
[27 feb 2018 19:26:21,233][DEBUG][][] Creating shared HTTP client 
[27 feb 2018 19:26:21,233][DEBUG][][] --------- protocolHandShake:[TLSv1.2]-------- 
[27 feb 2018 19:26:21,264][DEBUG][][] Shared HTTP client created successfully! 
[27 feb 2018 19:26:21,264][INFO ][][] Starting IdleHTTPConnectionEvictor task (evictionPeriod=5000) 
[27 feb 2018 19:26:21,327][DEBUG][][] getting the inputStream from fileName:[ADR.properties] 
[27 feb 2018 19:26:21,327][DEBUG][][] propertyValue:[ADBM] for propertyName:[DASHBOARD_NAMES] 
[27 feb 2018 19:26:21,327][DEBUG][][] propertyValue:[RemedyUsr] for propertyName:[REMEDY_AUTH_INFO_USER] 
[27 feb 2018 19:26:21,327][DEBUG][][] propertyValue:[RemedyPwd         ] for propertyName:[REMEDY_AUTH_INFO_PWD] 
[27 feb 2018 19:26:21,327][DEBUG][][] propertyValue:[https://dynatrace-sub-CA:8021/rest/management/dashboard/ADBM_TEST_REMEDY_INTEGRATION] for propertyName:[ADBM_URL] 
[27 feb 2018 19:26:21,327][DEBUG][][] propertyValue:[admin] for propertyName:[ADBM_USER] 
[27 feb 2018 19:26:21,343][DEBUG][][] propertyValue:[adradmin01] for propertyName:[ADBM_PWD] 
[27 feb 2018 19:26:21,343][DEBUG][][] propertyValue:[Dynatrace] for propertyName:[ADBM_FIRSTNAME] 
[27 feb 2018 19:26:21,343][DEBUG][][] propertyValue:[2-Significant/Large] for propertyName:[ADBM_IMPACT] 
[27 feb 2018 19:26:21,343][DEBUG][][] propertyValue:[Dynatrace] for propertyName:[ADBM_LASTNAME] 
[27 feb 2018 19:26:21,343][DEBUG][][] propertyValue:[Systems Management] for propertyName:[ADBM_REPORTED_SOURCE] 
[27 feb 2018 19:26:21,343][DEBUG][][] propertyValue:[Infrastructure Event] for propertyName:[ADBM_SERVICE_TYPE] 
[27 feb 2018 19:26:21,343][DEBUG][][] propertyValue:[New] for propertyName:[ADBM_TICKET_STATUS] 
[27 feb 2018 19:26:21,343][DEBUG][][] propertyValue:[2-High] for propertyName:[ADBM_URGENCY] 
[27 feb 2018 19:26:21,343][DEBUG][][] Configuration DONE 
[27 feb 2018 19:26:21,374][INFO ][C0A838015A95A2CD0001DC3B][1] Flow RemedyIncidentdBuilder Engine Called... 
[27 feb 2018 19:26:21,374][INFO ][C0A838015A95A2CD0001DC3B][1] service:[it.reply.sytel.adr.services.impl.GetDynatraceIncident] called ...  
[27 feb 2018 19:26:21,374][DEBUG][C0A838015A95A2CD0001DC3B][1] the Name for app:[ADBM] is [ADBM] 
[27 feb 2018 19:26:21,374][DEBUG][C0A838015A95A2CD0001DC3B][1] the URL for app:[ADBM] is [https://dynatrace-sub-CA:8021/rest/management/dashboard/ADBM_TEST_REMEDY_INTEGRATION] 
[27 feb 2018 19:26:21,374][DEBUG][C0A838015A95A2CD0001DC3B][1] the USR for app:[ADBM] is [admin] 
[27 feb 2018 19:26:21,374][DEBUG][C0A838015A95A2CD0001DC3B][1] the PWD for app:[ADBM] is [adradmin01] 
[27 feb 2018 19:26:21,374][DEBUG][C0A838015A95A2CD0001DC3B][1] calling the console:[https://dynatrace-sub-CA:8021/rest/management/dashboard/ADBM_TEST_REMEDY_INTEGRATION] with user[admin] pwd=adradmin01... 
[27 feb 2018 19:26:21,390][DEBUG][C0A838015A95A2CD0001DC3B][1] Executing POST with basic authentication 
[27 feb 2018 19:26:21,421][DEBUG][C0A838015A95A2CD0001DC3B][1] SOAP HTTP request headers: 
[27 feb 2018 19:26:21,421][INFO ][C0A838015A95A2CD0001DC3B][1] 	name=Authorization, value=Basic YWRtaW46YWRyYWRtaW4wMQ== 
[27 feb 2018 19:26:22,577][ERROR][C0A838015A95A2CD0001DC3B][1] Error while invoking URL:[] 
org.apache.http.conn.HttpHostConnectException: Connection to https://dynatrace-sub-CA:8021 refused
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:158)
	at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:149)
	at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:121)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:562)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:415)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:820)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:754)
	at it.reply.sytel.adr.common.ws.SharedHTTPSClient.invokeGet(SharedHTTPSClient.java:343)
	at it.reply.sytel.adr.dynatraceClient.imp.RestClientImpl.invokeRestService(RestClientImpl.java:36)
	at it.reply.sytel.adr.dynatraceClient.imp.DynatraceClientImpl.getDynatraceIncidents(DynatraceClientImpl.java:29)
	at it.reply.sytel.adr.services.impl.GetDynatraceIncident.perform(GetDynatraceIncident.java:50)
	at it.reply.sytel.adr.core.services.service.AbstractService.execute(AbstractService.java:67)
	at it.reply.sytel.adr.engine.RemedyIncidetBuilderEngine.executeFlow(RemedyIncidetBuilderEngine.java:57)
	at it.reply.sytel.adr.main.ConnectorExecutor.execute(ConnectorExecutor.java:27)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:374)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:148)
	... 15 more
[27 feb 2018 19:26:22,577][DEBUG][C0A838015A95A2CD0001DC3B][1] Marking associated HTTP connection as NOT-reusable 
[27 feb 2018 19:26:22,577][ERROR][C0A838015A95A2CD0001DC3B][1] Exception on Flow Flow TestBuilder Engine 
it.reply.sytel.adr.services.exc.GetDynatraceIncidentException: Exception on GetDynatraceIncident; nested exception is: 
	it.reply.sytel.adr.dynatraceClient.exc.RestClientException: Exception on invoking the http:[https://dynatrace-sub-CA:8021/rest/management/dashboard/ADBM_TEST_REMEDY_INTEGRATION]; nested exception is: 
	it.reply.sytel.adr.common.ws.exc.HttpClientException: Error while invoking URL:[]
it.reply.sytel.adr.dynatraceClient.exc.RestClientException: Exception on invoking the http:[https://dynatrace-sub-CA:8021/rest/management/dashboard/ADBM_TEST_REMEDY_INTEGRATION]; nested exception is: 
	it.reply.sytel.adr.common.ws.exc.HttpClientException: Error while invoking URL:[]
it.reply.sytel.adr.common.ws.exc.HttpClientException: Error while invoking URL:[]
	at it.reply.sytel.adr.common.ws.SharedHTTPSClient.invokeGet(SharedHTTPSClient.java:376)
	at it.reply.sytel.adr.dynatraceClient.imp.RestClientImpl.invokeRestService(RestClientImpl.java:36)
	at it.reply.sytel.adr.dynatraceClient.imp.DynatraceClientImpl.getDynatraceIncidents(DynatraceClientImpl.java:29)
	at it.reply.sytel.adr.services.impl.GetDynatraceIncident.perform(GetDynatraceIncident.java:50)
	at it.reply.sytel.adr.core.services.service.AbstractService.execute(AbstractService.java:67)
	at it.reply.sytel.adr.engine.RemedyIncidetBuilderEngine.executeFlow(RemedyIncidetBuilderEngine.java:57)
	at it.reply.sytel.adr.main.ConnectorExecutor.execute(ConnectorExecutor.java:27)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)
Caused by: org.apache.http.conn.HttpHostConnectException: Connection to https://dynatrace-sub-CA:8021 refused
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:158)
	at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:149)
	at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:121)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:562)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:415)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:820)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:754)
	at it.reply.sytel.adr.common.ws.SharedHTTPSClient.invokeGet(SharedHTTPSClient.java:343)
	... 8 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:374)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:148)
	... 15 more
[27 feb 2018 19:26:30,011][INFO ][C0A838015A95A2D600028731][2] Flow RemedyIncidentdBuilder Engine Called... 
[27 feb 2018 19:26:30,011][INFO ][C0A838015A95A2D600028731][2] service:[it.reply.sytel.adr.services.impl.GetDynatraceIncident] called ...  
[27 feb 2018 19:26:30,011][DEBUG][C0A838015A95A2D600028731][2] the Name for app:[ADBM] is [ADBM] 
[27 feb 2018 19:26:30,011][DEBUG][C0A838015A95A2D600028731][2] the URL for app:[ADBM] is [https://dynatrace-sub-CA:8021/rest/management/dashboard/ADBM_TEST_REMEDY_INTEGRATION] 
[27 feb 2018 19:26:30,011][DEBUG][C0A838015A95A2D600028731][2] the USR for app:[ADBM] is [admin] 
[27 feb 2018 19:26:30,011][DEBUG][C0A838015A95A2D600028731][2] the PWD for app:[ADBM] is [adradmin01] 
[27 feb 2018 19:26:30,011][DEBUG][C0A838015A95A2D600028731][2] calling the console:[https://dynatrace-sub-CA:8021/rest/management/dashboard/ADBM_TEST_REMEDY_INTEGRATION] with user[admin] pwd=adradmin01... 
[27 feb 2018 19:26:30,011][DEBUG][C0A838015A95A2D600028731][2] Executing POST with basic authentication 
[27 feb 2018 19:26:30,011][DEBUG][C0A838015A95A2D600028731][2] SOAP HTTP request headers: 
[27 feb 2018 19:26:30,011][INFO ][C0A838015A95A2D600028731][2] 	name=Authorization, value=Basic YWRtaW46YWRyYWRtaW4wMQ== 
[27 feb 2018 19:26:31,060][ERROR][C0A838015A95A2D600028731][2] Error while invoking URL:[] 
org.apache.http.conn.HttpHostConnectException: Connection to https://dynatrace-sub-CA:8021 refused
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:158)
	at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:149)
	at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:121)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:562)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:415)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:820)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:754)
	at it.reply.sytel.adr.common.ws.SharedHTTPSClient.invokeGet(SharedHTTPSClient.java:343)
	at it.reply.sytel.adr.dynatraceClient.imp.RestClientImpl.invokeRestService(RestClientImpl.java:36)
	at it.reply.sytel.adr.dynatraceClient.imp.DynatraceClientImpl.getDynatraceIncidents(DynatraceClientImpl.java:29)
	at it.reply.sytel.adr.services.impl.GetDynatraceIncident.perform(GetDynatraceIncident.java:50)
	at it.reply.sytel.adr.core.services.service.AbstractService.execute(AbstractService.java:67)
	at it.reply.sytel.adr.engine.RemedyIncidetBuilderEngine.executeFlow(RemedyIncidetBuilderEngine.java:57)
	at it.reply.sytel.adr.main.ConnectorExecutor.execute(ConnectorExecutor.java:27)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:374)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:148)
	... 15 more
[27 feb 2018 19:26:31,075][DEBUG][C0A838015A95A2D600028731][2] Marking associated HTTP connection as NOT-reusable 
[27 feb 2018 19:26:31,075][ERROR][C0A838015A95A2D600028731][2] Exception on Flow Flow TestBuilder Engine 
it.reply.sytel.adr.services.exc.GetDynatraceIncidentException: Exception on GetDynatraceIncident; nested exception is: 
	it.reply.sytel.adr.dynatraceClient.exc.RestClientException: Exception on invoking the http:[https://dynatrace-sub-CA:8021/rest/management/dashboard/ADBM_TEST_REMEDY_INTEGRATION]; nested exception is: 
	it.reply.sytel.adr.common.ws.exc.HttpClientException: Error while invoking URL:[]
it.reply.sytel.adr.dynatraceClient.exc.RestClientException: Exception on invoking the http:[https://dynatrace-sub-CA:8021/rest/management/dashboard/ADBM_TEST_REMEDY_INTEGRATION]; nested exception is: 
	it.reply.sytel.adr.common.ws.exc.HttpClientException: Error while invoking URL:[]
it.reply.sytel.adr.common.ws.exc.HttpClientException: Error while invoking URL:[]
	at it.reply.sytel.adr.common.ws.SharedHTTPSClient.invokeGet(SharedHTTPSClient.java:376)
	at it.reply.sytel.adr.dynatraceClient.imp.RestClientImpl.invokeRestService(RestClientImpl.java:36)
	at it.reply.sytel.adr.dynatraceClient.imp.DynatraceClientImpl.getDynatraceIncidents(DynatraceClientImpl.java:29)
	at it.reply.sytel.adr.services.impl.GetDynatraceIncident.perform(GetDynatraceIncident.java:50)
	at it.reply.sytel.adr.core.services.service.AbstractService.execute(AbstractService.java:67)
	at it.reply.sytel.adr.engine.RemedyIncidetBuilderEngine.executeFlow(RemedyIncidetBuilderEngine.java:57)
	at it.reply.sytel.adr.main.ConnectorExecutor.execute(ConnectorExecutor.java:27)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:557)
Caused by: org.apache.http.conn.HttpHostConnectException: Connection to https://dynatrace-sub-CA:8021 refused
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:158)
	at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:149)
	at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:121)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:562)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:415)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:820)
	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:754)
	at it.reply.sytel.adr.common.ws.SharedHTTPSClient.invokeGet(SharedHTTPSClient.java:343)
	... 8 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:374)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:148)
	... 15 more
[27 feb 2018 19:26:40,010][INFO ][C0A838015A95A2E000031869][3] Flow RemedyIncidentdBuilder Engine Called... 
[27 feb 2018 19:26:40,010][INFO ][C0A838015A95A2E000031869][3] service:[it.reply.sytel.adr.services.impl.GetDynatraceIncident] called ...  
[27 feb 2018 19:26:40,010][DEBUG][C0A838015A95A2E000031869][3] the Name for app:[ADBM] is [ADBM] 
[27 feb 2018 19:26:40,010][DEBUG][C0A838015A95A2E000031869][3] the URL for app:[ADBM] is [https://dynatrace-sub-CA:8021/rest/management/dashboard/ADBM_TEST_REMEDY_INTEGRATION] 
[27 feb 2018 19:26:40,010][DEBUG][C0A838015A95A2E000031869][3] the USR for app:[ADBM] is [admin] 
[27 feb 2018 19:26:40,010][DEBUG][C0A838015A95A2E000031869][3] the PWD for app:[ADBM] is [adradmin01] 
[27 feb 2018 19:26:40,010][DEBUG][C0A838015A95A2E000031869][3] calling the console:[https://dynatrace-sub-CA:8021/rest/management/dashboard/ADBM_TEST_REMEDY_INTEGRATION] with user[admin] pwd=adradmin01... 
[27 feb 2018 19:26:40,010][DEBUG][C0A838015A95A2E000031869][3] Executing POST with basic authentication 
[27 feb 2018 19:26:40,010][DEBUG][C0A838015A95A2E000031869][3] SOAP HTTP request headers: 
[27 feb 2018 19:26:40,010][INFO ][C0A838015A95A2E000031869][3] 	name=Authorization, value=Basic YWRtaW46YWRyYWRtaW4wMQ== 
